#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

// Register The Auto Loader
if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
} else {
    echo "Vendor dependencies not installed yet. Please run 'composer install' first.\n";
    exit(1);
}

// Bootstrap Laravel and handle the command...
$status = (require_once __DIR__.'/bootstrap/app.php')
    ->handleCommand(new Symfony\Component\Console\Input\ArgvInput);

exit($status);
